### ISSUE TITLE
Adding quick sort to sorting algorithms in cpp

### ISSUE THREAD

**Issue by deveshidwivedi** [ossamamehmood/Hacktoberfest#6276]
I can add the quick sort algorithm under sorting algorithms in C++. It is an important algorithm and used widely. Please assign it to me under hacktoberfest 2023

**Comment by MysticWanderer142** [comment]
Assign this to me.

**Comment by nikunjgupta609** [comment]
@deveshidwivedi please assign me this issue, please

**Comment by Debashis-11101-srijib** [comment]
Please assign this to me.

**Comment by Kedarnath-Rothe** [comment]
Please assign to me
