### ISSUE TITLE
Knapsack 0-1 Problem in DP

### ISSUE THREAD

**Issue by Somnath-Mishra** [ossamamehmood/Hacktoberfest#6285]
I going to add knapsack 0-1 problem

**Comment by akshaydubey05** [comment]
Hey @ossamamehmood  Please assign this task to me i will be easily able to do it as i have expertise in DSA and CP .

**Comment by shakti2002** [comment]
I want to work on this issue please assign this to me

**Comment by Kedarnath-Rothe** [comment]
Please assign to me
