### ISSUE TITLE
Add simple Login Registration System in CPP

### ISSUE THREAD

**Issue by joshiadarshx** [ossamamehmood/Hacktoberfest#6359]
**Problem:**
Many individuals learning C++ face challenges in understanding the implementation of fundamental concepts in real-world scenarios. Specifically, a significant gap exists in resources demonstrating how to create a login and registration system using C++, which is a common task in software development.

**Solution:**
I propose the creation of a login and registration system project implemented in C++. This project should cover essential concepts such as classes, objects, file handling, data validation, and error handling. It should be well-structured, allowing beginners to grasp the principles of object-oriented programming (OOP) while working on a practical application. The project should include detailed comments within the code, explaining the logic behind each step. Additionally, a step-by-step guide should be provided to assist learners in understanding the implementation process. By offering this resource, beginners can apply their theoretical knowledge in a tangible context, reinforcing their understanding of C++ programming concepts.

**Comment by joshiadarshx** [comment]
@ossamamehmood  and maintainers can you please assign it to me so I can contribute

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by Sa2003hil** [comment]
**Hey @ossamamehmood  !
I want to work on this issue #6359 please add hacktoberfest-accepted or hacktoberfest label to this issue.
Best Regards
@Sa2003hil**
