### ISSUE TITLE
Why are so many repos excluded?

### ISSUE THREAD

**Issue by iniakuncoc2** [ossamamehmood/Hacktoberfest#6445]
so many repos are excluded, why? is it against the rules?

**Comment by azizarizaldi** [comment]
yup, that's right,
because the repo does not comply with hacktoberfest rules (not eligible).

**Comment by ossamamehmood** [comment]
YES

**Comment by ossamamehmood** [comment]
YES

**Comment by ossamamehmood** [comment]
yes

**Comment by ossamamehmood** [comment]
It doesn't meet hacktoberfest rule but we have created a new spam-free repo!
