### ISSUE TITLE
Seeking a way to clone relevant part of the repo, instead of all items in it

### ISSUE THREAD

**Issue by onukwilip** [ossamamehmood/Hacktoberfest#6473]
Please, cloning the repository requires a LOT of internet connection. Is there a different way to only clone a section of the repository?

**Comment by Swish78** [comment]
The easiest way to clone a specific section of a Git repository is to use a combination of shallow cloning and sparse checkout. This method allows you to fetch only a limited number of commits and then work with specific files or directories of your choice.

Here's a step-by-step guide:

1. **Shallow Clone**:
   Clone the repository with a limited commit history by specifying the `--depth` option. For example, to clone only the last 3 commits:

   ```shell
   git clone --depth 3 <repository_url>
   ```

2. **Sparse Checkout**:
   Enable sparse-checkout to work with specific files or directories. You can do this after the shallow clone:

   ```shell
   cd <repository_directory>  # Navigate to the cloned repository directory

   git sparse-checkout init  # Initialize sparse-checkout
   git sparse-checkout set <path/to/directory>  # Specify the directory you want
   ```

This approach will give you a limited commit history and allow you to work with only the specified files or directories, making it the easiest way to clone and work with a specific section of a Git repository.

**Comment by onukwilip** [comment]
Thanks ☺️
