### ISSUE TITLE
Why while creating PR its saying python CL failed

### ISSUE THREAD

**Issue by joshiadarshx** [ossamamehmood/Hacktoberfest#6587]

**Comment by gaurovgiri** [comment]
Yes , it seems like there are some broken files that fails the python test.

**Comment by aayush105** [comment]
Yeah i reviewed the broken files and it need to be fixed, please fix the issue @ossamamehmood .

**Comment by joshiadarshx** [comment]
> Yeah i reviewed the broken files and it need to be fixed, please fix the issue @ossamamehmood .
> 

Is it my fault or the repo creator's

**Comment by joshiadarshx** [comment]
> Yes , it seems like there are some broken files that fails the python test.

Is it my fault or repo creator's?

**Comment by adarshherohoo** [comment]
@ossamamehmood can you please also check the attached PR no with the above comment
