### ISSUE TITLE
Add the star pattern in C code

### ISSUE THREAD

**Issue by Starswaty** [ossamamehmood/Hacktoberfest#6656]
I want to add the star pattern in C code. Please assign me this issue @ossamamehmood

**Comment by chinmay7016** [comment]
@ossamamehmood pls merge it

**Comment by aasthaagarwal2003** [comment]
Hey can I help

**Comment by Makhdum412** [comment]
@ossamamehmood heyyy, i want to contribute. pls assign me

#include <stdio.h>

int main() {
    int rows, i, j;

    printf("Enter the number of rows: ");
    scanf("%d", &rows);

    for (i = 1; i <= rows; i++) {
        for (j = 1; j <= i; j++) {
            printf("* ");
        }
        printf("\n");
    }

    return 0;
}
![image](https://github.com/ossamamehmood/Hacktoberfest/assets/75497174/f5733484-4093-4393-9b84-30353d6a4f8b)

**Comment by HriGrit** [comment]
hey @ossamamehmood , i can most definitely work on the issue described by you. Let me know if you would be interested to have me on board.

**Comment by subh737** [comment]
hey @ossamamehmood please assign me the task

**Comment by kartikey-singh-k** [comment]
kindly assign me

**Comment by VBPMP** [comment]
please assign me this issue
