### ISSUE TITLE
Expense Tracker

### ISSUE THREAD

**Issue by kumarharshh** [ossamamehmood/Hacktoberfest#6727]
Hi, 
I want to add a expense tracker project using html, css, js and react.js too, Can you please assign this issue to me?

**Comment by Makhdum412** [comment]
@ossamamehmood heyyy,
Can u pls assign me this issue.
![image](https://github.com/ossamamehmood/Hacktoberfest/assets/75497174/f214a9b4-1116-4789-bac7-a6a09dc1eefe)

@ossamamehmood I'll work more on the CSS and styling if you assign me the issue. Thank you!!!

**Comment by kumarharshh** [comment]
> @ossamamehmood heyyy, Can u pls assign me this issue. ![image](https://user-images.githubusercontent.com/75497174/275645951-f214a9b4-1116-4789-bac7-a6a09dc1eefe.png)
> 
> @ossamamehmood I'll work more on the CSS and styling if you assign me the issue. Thank you!!!

You may solve this, but you have to take into consideration that all the data should be saved even when you reload
