### ISSUE TITLE
Plan Tasks [ tasks_planning  app_flutter]

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [ossamamehmood/Hacktoberfest#6742]
Task Planning app.

Login, sign up with fire_base authentication.

Each and every user have their own tasks or plans to do.
In this after user logged in he can see his plans if already present, if not he can plan or create his tasks, and he can update, he can also delete his tasks or plans after he done with his each task.

Can you please assign this to me , I am interested to contribute myself in hacktoberfest _23 : )

**Comment by iamdiinesh** [comment]
hello @Bharath-KumarReddy , i am interested in the issue and want to contribute into it under the hacktoberfest and hactoberfest-accepted can you assignt the project to me?
