### ISSUE TITLE
Implement Shell Sort Algorithm in TypeScript

### ISSUE THREAD

**Issue by purnasth** [ossamamehmood/Hacktoberfest#6827]
# Issue Title: Implement Shell Sort Algorithm in TypeScript (Ascending Order)

## Issue Description:
I'd like to contribute to this repository by implementing the Shell Sort algorithm in TypeScript.

## Proposed Changes:
- Implement the Shell Sort algorithm in TypeScript.
- Ensure the algorithm correctly sorts data in ascending order.

I kindly request to be assigned to this issue to proceed with the implementation.

**Comment by Shubhamraj2841** [comment]
// Shell sort in Java programming

import java.util.Arrays;

// Shell sort
class ShellSort {

  // Rearrange elements at each n/2, n/4, n/8, ... intervals
  void shellSort(int array[], int n) {
  for (int interval = n / 2; interval > 0; interval /= 2) {
    for (int i = interval; i < n; i += 1) {
    int temp = array[i];
    int j;
    for (j = i; j >= interval && array[j - interval] > temp; j -= interval) {
      array[j] = array[j - interval];
    }
    array[j] = temp;
    }
  }
  }

  // Driver code
  public static void main(String args[]) {
  int[] data = { 9, 8, 3, 7, 5, 6, 4, 1 };
  int size = data.length;
  ShellSort ss = new ShellSort();
  ss.shellSort(data, size);
  System.out.println("Sorted Array in Ascending Order: ");
  System.out.println(Arrays.toString(data));
  }
}

**Comment by purnasth** [comment]
Hello @Shubhamraj2841, you may create a new similar issue for this. 
Example: Implement Shell Sort Algorithm in Java (Ascending Order)
